input_lv = [
    {
        'X': (0, 101, 1),
        'name': 'Age',
        'terms': {
            'young': ('trapmf', 0, 0, 18, 25),
            'adult': ('trapmf', 18, 25, 30, 40),
            'middle age': ('trimf', 30, 45, 60),
            'old': ('trapmf', 50, 60, 100, 100),
        }
    },

    {
        'X': (0, 251, 1),
        'name': 'Height',
        'terms': {
            'short': ('trapmf', 0, 0, 140, 160),
            'average': ('trapmf', 150, 165, 170, 190),
            'tall': ('trapmf', 170, 190, 250, 250),
        }
    },

    {
        'X': (0, 50.01, 0.01),
        'name': 'Body type',
        'terms': {
            'thin': ('trapmf', 0, 0, 16, 18.5),
            'average': ('trapmf', 16, 18.5, 20, 25),
            'athletic': ('trimf', 16, 25, 30),
            'extra pound': ('trapmf', 25, 35, 50, 50),
        }
    },

    {
        'X': (0, 100_001, 1),
        'name': 'Income',
        'terms': {
            'low': ('trapmf', 0, 0, 2_000, 3_500),
            'medium': ('trapmf', 2_000, 3_500, 7_000, 12_000),
            'high': ('trapmf', 7_000, 24_000, 36_000, 60_000),
            'extremely high': ('trapmf', 40_000, 60_000, 100_000, 100_000),
        }
    }
]

output_l = {
    'X': (0, 10.1, 0.1),
    'name': 'Attractive level',
    'terms': {
        'none to very little': ('trapmf', 0, 0, 0.5, 1),
        'very low': ('trimf', 0, 2, 3),
        'low': ('trapmf', 2, 3, 4, 5),
        'medium': ('trimf', 4, 5, 6),
        'above medium': ('trimf', 5, 6, 7),
        'high': ('trapmf', 6, 7, 8, 9),
        'extremely high': ('trapmf', 7, 9, 10, 10),
    }
}


rule_bas = [
    (('young', 'short', 'thin', 'low'), 'medium'),
    (('young', 'short', 'thin', 'medium'), 'above medium'),
    (('young', 'short', 'thin', 'high'), 'very low'),
    (('young', 'short', 'thin', 'extremely high'), 'very low'),
    (('young', 'short', 'average', 'low'), 'above medium'),
    (('young', 'short', 'average', 'medium'), 'high'),
    (('young', 'short', 'average', 'high'), 'medium'),
    (('young', 'short', 'average', 'extremely high'), 'extremely high'),
    (('young', 'short', 'athletic', 'low'), 'above medium'),
    (('young', 'short', 'athletic', 'medium'), 'above medium'),
    (('young', 'short', 'athletic', 'high'), 'none to very little'),
    (('young', 'short', 'athletic', 'extremely high'), 'extremely high'),
    (('young', 'short', 'extra pound', 'low'), 'medium'),
    (('young', 'short', 'extra pound', 'medium'), 'low'),
    (('young', 'short', 'extra pound', 'high'), 'high'),
    (('young', 'short', 'extra pound', 'extremely high'), 'medium'),
    (('young', 'average', 'thin', 'low'), 'low'),
    (('young', 'average', 'thin', 'medium'), 'high'),
    (('young', 'average', 'thin', 'high'), 'very low'),
    (('young', 'average', 'thin', 'extremely high'), 'high'),
    (('young', 'average', 'average', 'low'), 'none to very little'),
    (('young', 'average', 'average', 'medium'), 'very low'),
    (('young', 'average', 'average', 'high'), 'extremely high'),
    (('young', 'average', 'average', 'extremely high'), 'medium'),
    (('young', 'average', 'athletic', 'low'), 'above medium'),
    (('young', 'average', 'athletic', 'medium'), 'high'),
    (('young', 'average', 'athletic', 'high'), 'none to very little'),
    (('young', 'average', 'athletic', 'extremely high'), 'medium'),
    (('young', 'average', 'extra pound', 'low'), 'low'),
    (('young', 'average', 'extra pound', 'medium'), 'none to very little'),
    (('young', 'average', 'extra pound', 'high'), 'high'),
    (('young', 'average', 'extra pound', 'extremely high'), 'none to very little'),
    (('young', 'tall', 'thin', 'low'), 'high'),
    (('young', 'tall', 'thin', 'medium'), 'above medium'),
    (('young', 'tall', 'thin', 'high'), 'very low'),
    (('young', 'tall', 'thin', 'extremely high'), 'extremely high'),
    (('young', 'tall', 'average', 'low'), 'above medium'),
    (('young', 'tall', 'average', 'medium'), 'low'),
    (('young', 'tall', 'average', 'high'), 'extremely high'),
    (('young', 'tall', 'average', 'extremely high'), 'very low'),
    (('young', 'tall', 'athletic', 'low'), 'none to very little'),
    (('young', 'tall', 'athletic', 'medium'), 'very low'),
    (('young', 'tall', 'athletic', 'high'), 'extremely high'),
    (('young', 'tall', 'athletic', 'extremely high'), 'low'),
    (('young', 'tall', 'extra pound', 'low'), 'none to very little'),
    (('young', 'tall', 'extra pound', 'medium'), 'extremely high'),
    (('young', 'tall', 'extra pound', 'high'), 'low'),
    (('young', 'tall', 'extra pound', 'extremely high'), 'medium'),
    (('adult', 'short', 'thin', 'low'), 'none to very little'),
    (('adult', 'short', 'thin', 'medium'), 'very low'),
    (('adult', 'short', 'thin', 'high'), 'above medium'),
    (('adult', 'short', 'thin', 'extremely high'), 'medium'),
    (('adult', 'short', 'average', 'low'), 'extremely high'),
    (('adult', 'short', 'average', 'medium'), 'very low'),
    (('adult', 'short', 'average', 'high'), 'very low'),
    (('adult', 'short', 'average', 'extremely high'), 'extremely high'),
    (('adult', 'short', 'athletic', 'low'), 'low'),
    (('adult', 'short', 'athletic', 'medium'), 'extremely high'),
    (('adult', 'short', 'athletic', 'high'), 'low'),
    (('adult', 'short', 'athletic', 'extremely high'), 'very low'),
    (('adult', 'short', 'extra pound', 'low'), 'above medium'),
    (('adult', 'short', 'extra pound', 'medium'), 'high'),
    (('adult', 'short', 'extra pound', 'high'), 'high'),
    (('adult', 'short', 'extra pound', 'extremely high'), 'low'),
    (('adult', 'average', 'thin', 'low'), 'above medium'),
    (('adult', 'average', 'thin', 'medium'), 'medium'),
    (('adult', 'average', 'thin', 'high'), 'very low'),
    (('adult', 'average', 'thin', 'extremely high'), 'none to very little'),
    (('adult', 'average', 'average', 'low'), 'low'),
    (('adult', 'average', 'average', 'medium'), 'extremely high'),
    (('adult', 'average', 'average', 'high'), 'high'),
    (('adult', 'average', 'average', 'extremely high'), 'above medium'),
    (('adult', 'average', 'athletic', 'low'), 'above medium'),
    (('adult', 'average', 'athletic', 'medium'), 'above medium'),
    (('adult', 'average', 'athletic', 'high'), 'very low'),
    (('adult', 'average', 'athletic', 'extremely high'), 'very low'),
    (('adult', 'average', 'extra pound', 'low'), 'high'),
    (('adult', 'average', 'extra pound', 'medium'), 'very low'),
    (('adult', 'average', 'extra pound', 'high'), 'high'),
    (('adult', 'average', 'extra pound', 'extremely high'), 'none to very little'),
    (('adult', 'tall', 'thin', 'low'), 'none to very little'),
    (('adult', 'tall', 'thin', 'medium'), 'extremely high'),
    (('adult', 'tall', 'thin', 'high'), 'above medium'),
    (('adult', 'tall', 'thin', 'extremely high'), 'very low'),
    (('adult', 'tall', 'average', 'low'), 'low'),
    (('adult', 'tall', 'average', 'medium'), 'low'),
    (('adult', 'tall', 'average', 'high'), 'above medium'),
    (('adult', 'tall', 'average', 'extremely high'), 'low'),
    (('adult', 'tall', 'athletic', 'low'), 'above medium'),
    (('adult', 'tall', 'athletic', 'medium'), 'medium'),
    (('adult', 'tall', 'athletic', 'high'), 'low'),
    (('adult', 'tall', 'athletic', 'extremely high'), 'above medium'),
    (('adult', 'tall', 'extra pound', 'low'), 'above medium'),
    (('adult', 'tall', 'extra pound', 'medium'), 'none to very little'),
    (('adult', 'tall', 'extra pound', 'high'), 'medium'),
    (('adult', 'tall', 'extra pound', 'extremely high'), 'extremely high'),
    (('middle age', 'short', 'thin', 'low'), 'none to very little'),
    (('middle age', 'short', 'thin', 'medium'), 'extremely high'),
    (('middle age', 'short', 'thin', 'high'), 'high'),
    (('middle age', 'short', 'thin', 'extremely high'), 'above medium'),
    (('middle age', 'short', 'average', 'low'), 'medium'),
    (('middle age', 'short', 'average', 'medium'), 'high'),
    (('middle age', 'short', 'average', 'high'), 'extremely high'),
    (('middle age', 'short', 'average', 'extremely high'), 'high'),
    (('middle age', 'short', 'athletic', 'low'), 'extremely high'),
    (('middle age', 'short', 'athletic', 'medium'), 'medium'),
    (('middle age', 'short', 'athletic', 'high'), 'medium'),
    (('middle age', 'short', 'athletic', 'extremely high'), 'medium'),
    (('middle age', 'short', 'extra pound', 'low'), 'above medium'),
    (('middle age', 'short', 'extra pound', 'medium'), 'above medium'),
    (('middle age', 'short', 'extra pound', 'high'), 'none to very little'),
    (('middle age', 'short', 'extra pound', 'extremely high'), 'low'),
    (('middle age', 'average', 'thin', 'low'), 'very low'),
    (('middle age', 'average', 'thin', 'medium'), 'very low'),
    (('middle age', 'average', 'thin', 'high'), 'very low'),
    (('middle age', 'average', 'thin', 'extremely high'), 'none to very little'),
    (('middle age', 'average', 'average', 'low'), 'none to very little'),
    (('middle age', 'average', 'average', 'medium'), 'above medium'),
    (('middle age', 'average', 'average', 'high'), 'low'),
    (('middle age', 'average', 'average', 'extremely high'), 'high'),
    (('middle age', 'average', 'athletic', 'low'), 'none to very little'),
    (('middle age', 'average', 'athletic', 'medium'), 'low'),
    (('middle age', 'average', 'athletic', 'high'), 'medium'),
    (('middle age', 'average', 'athletic', 'extremely high'), 'very low'),
    (('middle age', 'average', 'extra pound', 'low'), 'very low'),
    (('middle age', 'average', 'extra pound', 'medium'), 'above medium'),
    (('middle age', 'average', 'extra pound', 'high'), 'very low'),
    (('middle age', 'average', 'extra pound', 'extremely high'), 'extremely high'),
    (('middle age', 'tall', 'thin', 'low'), 'none to very little'),
    (('middle age', 'tall', 'thin', 'medium'), 'very low'),
    (('middle age', 'tall', 'thin', 'high'), 'none to very little'),
    (('middle age', 'tall', 'thin', 'extremely high'), 'high'),
    (('middle age', 'tall', 'average', 'low'), 'none to very little'),
    (('middle age', 'tall', 'average', 'medium'), 'none to very little'),
    (('middle age', 'tall', 'average', 'high'), 'extremely high'),
    (('middle age', 'tall', 'average', 'extremely high'), 'medium'),
    (('middle age', 'tall', 'athletic', 'low'), 'medium'),
    (('middle age', 'tall', 'athletic', 'medium'), 'above medium'),
    (('middle age', 'tall', 'athletic', 'high'), 'low'),
    (('middle age', 'tall', 'athletic', 'extremely high'), 'high'),
    (('middle age', 'tall', 'extra pound', 'low'), 'above medium'),
    (('middle age', 'tall', 'extra pound', 'medium'), 'none to very little'),
    (('middle age', 'tall', 'extra pound', 'high'), 'very low'),
    (('middle age', 'tall', 'extra pound', 'extremely high'), 'none to very little'),
    (('old', 'short', 'thin', 'low'), 'extremely high'),
    (('old', 'short', 'thin', 'medium'), 'medium'),
    (('old', 'short', 'thin', 'high'), 'very low'),
    (('old', 'short', 'thin', 'extremely high'), 'none to very little'),
    (('old', 'short', 'average', 'low'), 'extremely high'),
    (('old', 'short', 'average', 'medium'), 'low'),
    (('old', 'short', 'average', 'high'), 'medium'),
    (('old', 'short', 'average', 'extremely high'), 'low'),
    (('old', 'short', 'athletic', 'low'), 'above medium'),
    (('old', 'short', 'athletic', 'medium'), 'none to very little'),
    (('old', 'short', 'athletic', 'high'), 'none to very little'),
    (('old', 'short', 'athletic', 'extremely high'), 'low'),
    (('old', 'short', 'extra pound', 'low'), 'low'),
    (('old', 'short', 'extra pound', 'medium'), 'medium'),
    (('old', 'short', 'extra pound', 'high'), 'above medium'),
    (('old', 'short', 'extra pound', 'extremely high'), 'above medium'),
    (('old', 'average', 'thin', 'low'), 'above medium'),
    (('old', 'average', 'thin', 'medium'), 'medium'),
    (('old', 'average', 'thin', 'high'), 'extremely high'),
    (('old', 'average', 'thin', 'extremely high'), 'very low'),
    (('old', 'average', 'average', 'low'), 'above medium'),
    (('old', 'average', 'average', 'medium'), 'none to very little'),
    (('old', 'average', 'average', 'high'), 'medium'),
    (('old', 'average', 'average', 'extremely high'), 'extremely high'),
    (('old', 'average', 'athletic', 'low'), 'low'),
    (('old', 'average', 'athletic', 'medium'), 'extremely high'),
    (('old', 'average', 'athletic', 'high'), 'above medium'),
    (('old', 'average', 'athletic', 'extremely high'), 'low'),
    (('old', 'average', 'extra pound', 'low'), 'medium'),
    (('old', 'average', 'extra pound', 'medium'), 'above medium'),
    (('old', 'average', 'extra pound', 'high'), 'very low'),
    (('old', 'average', 'extra pound', 'extremely high'), 'above medium'),
    (('old', 'tall', 'thin', 'low'), 'none to very little'),
    (('old', 'tall', 'thin', 'medium'), 'medium'),
    (('old', 'tall', 'thin', 'high'), 'none to very little'),
    (('old', 'tall', 'thin', 'extremely high'), 'medium'),
    (('old', 'tall', 'average', 'low'), 'none to very little'),
    (('old', 'tall', 'average', 'medium'), 'above medium'),
    (('old', 'tall', 'average', 'high'), 'high'),
    (('old', 'tall', 'average', 'extremely high'), 'very low'),
    (('old', 'tall', 'athletic', 'low'), 'low'),
    (('old', 'tall', 'athletic', 'medium'), 'very low'),
    (('old', 'tall', 'athletic', 'high'), 'above medium'),
    (('old', 'tall', 'athletic', 'extremely high'), 'extremely high'),
    (('old', 'tall', 'extra pound', 'low'), 'extremely high'),
    (('old', 'tall', 'extra pound', 'medium'), 'low'),
    (('old', 'tall', 'extra pound', 'high'), 'low'),
    (('old', 'tall', 'extra pound', 'extremely high'), 'none to very little'),
]